import type { NextPage } from "next";
import PagesGallery from "../components/PagesGallery";

const Home: NextPage = () => {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PagesGallery />
    </div>
  );
};

export default Home;
